// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalkThroughAPI.Data;

#nullable disable

namespace TalkThroughAPI.Migrations
{
    [DbContext(typeof(TthroughContext))]
    [Migration("20251031153409_CommunityAdmins")]
    partial class CommunityAdmins
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TalkThroughAPI.Models.Call", b =>
                {
                    b.Property<string>("CallId")
                        .HasColumnType("Varchar(40)");

                    b.Property<DateTime>("CallEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CallStart")
                        .HasColumnType("datetime2");

                    b.HasKey("CallId");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.Chat", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("Varchar(40)");

                    b.Property<DateTime>("ChatCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ChatPicture")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ChatId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.Communities", b =>
                {
                    b.Property<string>("CommunityId")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("CommunityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("CommunityPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.HasKey("CommunityId");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.CommunitiesChats", b =>
                {
                    b.Property<string>("IdChat")
                        .HasColumnType("Varchar(40)");

                    b.Property<string>("IdCommunity")
                        .HasColumnType("Varchar(40)");

                    b.HasKey("IdChat", "IdCommunity");

                    b.HasIndex("IdCommunity");

                    b.ToTable("CommunitiesChats");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.CommunitiesUsers", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("Varchar(40)");

                    b.Property<string>("UserName")
                        .HasColumnType("Varchar(40)");

                    b.Property<string>("CommunityId")
                        .HasColumnType("Varchar(40)");

                    b.Property<bool>("UserIsAdmin")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "UserName", "CommunityId");

                    b.HasIndex("CommunityId");

                    b.ToTable("CommunitiesUsers");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.Friends", b =>
                {
                    b.Property<string>("UserSenderId")
                        .HasColumnType("Varchar(40)");

                    b.Property<string>("UserReceiverId")
                        .HasColumnType("Varchar(40)");

                    b.Property<string>("UserSenderUsername")
                        .HasColumnType("Varchar(40)");

                    b.Property<string>("UserReceiverUsername")
                        .HasColumnType("Varchar(40)");

                    b.Property<bool>("RequestAccepted")
                        .HasColumnType("bit");

                    b.HasKey("UserSenderId", "UserReceiverId", "UserSenderUsername", "UserReceiverUsername");

                    b.HasIndex("UserReceiverId", "UserReceiverUsername");

                    b.HasIndex("UserSenderId", "UserSenderUsername");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.Messages", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("Varchar(40)");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MessageSentTime")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.MessagesChats", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("Varchar(40)");

                    b.Property<string>("MessageId")
                        .HasColumnType("Varchar(40)");

                    b.HasKey("ChatId", "MessageId");

                    b.HasIndex("MessageId");

                    b.ToTable("MessagesChats");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("Varchar(40)");

                    b.Property<string>("UserName")
                        .HasColumnType("Varchar(40)");

                    b.Property<DateTime>("AccountCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("UserProfilePicture")
                        .HasColumnType("VARBINARY(MAX)");

                    b.HasKey("Id", "UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.UsersCalls", b =>
                {
                    b.Property<string>("CallId")
                        .HasColumnType("Varchar(40)");

                    b.Property<string>("UserId")
                        .HasColumnType("Varchar(40)");

                    b.Property<string>("UserName")
                        .HasColumnType("Varchar(40)");

                    b.HasKey("CallId", "UserId", "UserName");

                    b.HasIndex("UserId", "UserName");

                    b.ToTable("UsersCalls");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.UsersChats", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(40)");

                    b.HasKey("ChatId", "UserId", "UserName");

                    b.HasIndex("UserId", "UserName");

                    b.ToTable("ChatsUsers");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.CommunitiesChats", b =>
                {
                    b.HasOne("TalkThroughAPI.Models.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalkThroughAPI.Models.Communities", "Community")
                        .WithMany()
                        .HasForeignKey("IdCommunity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.CommunitiesUsers", b =>
                {
                    b.HasOne("TalkThroughAPI.Models.Communities", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TalkThroughAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId", "UserName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.Friends", b =>
                {
                    b.HasOne("TalkThroughAPI.Models.User", "UserReceiver")
                        .WithMany()
                        .HasForeignKey("UserReceiverId", "UserReceiverUsername")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TalkThroughAPI.Models.User", "UserSender")
                        .WithMany()
                        .HasForeignKey("UserSenderId", "UserSenderUsername")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserReceiver");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.MessagesChats", b =>
                {
                    b.HasOne("TalkThroughAPI.Models.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalkThroughAPI.Models.Messages", "Message")
                        .WithMany("MessagesChats")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.UsersCalls", b =>
                {
                    b.HasOne("TalkThroughAPI.Models.Call", "Calls")
                        .WithMany()
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TalkThroughAPI.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("UserId", "UserName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Calls");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.UsersChats", b =>
                {
                    b.HasOne("TalkThroughAPI.Models.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TalkThroughAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId", "UserName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalkThroughAPI.Models.Messages", b =>
                {
                    b.Navigation("MessagesChats");
                });
#pragma warning restore 612, 618
        }
    }
}
